.PHONY: all ui backend run

all: ui backend

ui:
    cd ui && npm install && npm run dev

backend:
    cd backend && go build -o main .

run:
    cd ui && npm start & cd backend && ./main

clean:
    cd ui && rm -rf node_modules && rm -rf build
    cd backend && rm main