.PHONY: all ui backend run
all: ui backend
ui:
	cd ui && npm install && npm run dev
backend:
	cd backend && go run main.go .
run:
	tmux new-session -d -s ui 'cd ui && npm start'
	tmux new-session -d -s backend 'cd backend && ./main'
clean:
	cd ui && rm -rf node_modules && rm -rf build
	cd backend && rm main
kill:
	tmux kill-session -t ui
	tmux kill-session -t backend